Problem: syn 1.0.60 broke tia
Started getting errors like this:

```
error[E0599]: no variant or associated item named `__Nonexhaustive` found for enum `syn::Type` in the current scope
   |
87 |   syn::Type::__Nonexhaustive => panic!("tia not implemented feature: __Nonexhaustive, please write PR or Issue if you want the feature. #...
   |              ^^^^^^^^^^^^^^^
   |              |
   |              variant or associated item not found in `syn::Type`
   |              help: there is a variant with a similar name: `__TestExhaustive`
```

1.0.59 works fine

Solution: upgrade to 1.0.60